version: 0.2.{build}
image: Visual Studio 2019
install:
- cmd: |
    cd "C:\Tools\vcpkg"
    git pull > NUL
    .\bootstrap-vcpkg.bat > NUL
    cd %appveyor_build_folder%
before_build:
- cmd: vcpkg integrate install
- cmd: vcpkg upgrade --no-dry-run
- cmd: vcpkg install spdlog:x86-windows-static spdlog:x64-windows-static detours:x86-windows-static detours:x64-windows-static
configuration: Release
platform:
- x86
- x64
build:
  project: socksifier.sln
artifacts:
- path: 'bin**\*.dll'
cache:
- c:\tools\vcpkg\installed\